import cv2
img = cv2.imread("lisa.jpg")
grayImg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
blurImg = cv2.GaussianBlur(grayImg, (5,5), 0)
cannyImg = cv2.Canny(img, 100, 100)
dilatedImag = cv2.dilate(cannyImg, (5,5), iterations=2)
erodedImg = cv2.erode(dilatedImag, (5,5), iterations=5)
cv2.imshow("Lisa my Love", img)
cv2.imshow("Lis my Gray Love", grayImg)
cv2.imshow("Lisa my Blur Love", blurImg)
cv2.imshow("Lisa my Canny Love", cannyImg)
cv2.imshow("Lisa my dilated Love", dilatedImag)
cv2.imshow("Lisa my eroded Love", erodedImg)
cv2.waitKey(0)